"""Ingest Sahih al-Bukhari and Sahih Muslim (OpenITI / Shamela editions) into the corpus DB.

Ids: hadith:bukhari:<number>, hadith:muslim:<number> (the edition's own number, never inferred).
Narrations the source file does not number (Muslim, mostly Kitab al-Iman): INTERNAL id
hadith:muslim:u:<book>:<chapter>:<ordinal>, hadith_number = null, cited by book and chapter.
Grading metadata records the official package rule for the two Sahih collections; it is never
generated by a model (grading_generated_by_model = false, checked by validation V15).
No previous/next context links are created: adjacent hadith are not interpretive context.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

from app.corpus.common import PassageRecord, SourceRecord, insert_passages, insert_source
from app.corpus.openiti_hadith import parse_bukhari, parse_muslim
from app.services.normalizer import normalize_for_search, normalize_hadith_search

PARSERS = {"bukhari": parse_bukhari, "muslim": parse_muslim}


def ingest(conn: sqlite3.Connection, meta_path: Path, root: Path, corpus_version: str) -> dict[str, dict]:
    meta = json.loads(Path(meta_path).read_text(encoding="utf-8"))
    g = meta["grading"]
    out: dict[str, dict] = {}
    for col in meta["collections"]:
        raw = (root / col["file"]["local_path"]).read_text(encoding="utf-8")
        recs, stats = PARSERS[col["parser"]](raw)
        if stats["duplicates"]:
            raise RuntimeError(f"{col['source_id']}: duplicate numbers {stats['duplicates'][:10]}")
        sid = col["source_id"]
        insert_source(conn, SourceRecord(
            id=sid, source_type="hadith", title=col["title"], author=col["author"], edition=col["edition"],
            publisher=col["publisher"], source_url=col["source_url"],
            license_note=meta["license"]["reuse_status"] + ". " + meta["license"]["openiti"],
            verification_status=meta["status"], acquired_at=meta["acquisition"]["acquired_at"],
            corpus_version=corpus_version,
            metadata={
                "collection": col["collection"], "collection_ar": col["collection_ar"], "editor": col["editor"],
                "numbering": col["numbering"], "shamela_book_id": col["shamela_book_id"],
                "openiti_uri": col["openiti_uri"], "file_sha256": col["file"]["sha256"],
                "provenance": f"{meta['acquisition']['repository']} @ {meta['acquisition']['repository_commit']} "
                              f"{col['file']['repo_path']} (sha256 {col['file']['sha256']})",
                "grading_rule": g["rule"], "grading_scope_caveat": g["scope_caveat"],
                "gaps": stats["gaps"],
            },
        ))
        passages = []
        for i, r in enumerate(recs, start=1):
            if r.number is not None:
                pid, ref, locator = f"{sid}:{r.number}", str(r.number), None
            else:
                # no number in the source file: INTERNAL id + source locator; never a fabricated number
                pid = f"{sid}:u:{r.book_number}:{r.chapter_number}:{r.ordinal}"
                ref = f"u:{r.book_number}:{r.chapter_number}:{r.ordinal}"
                locator = {"book_number": r.book_number, "chapter_number": r.chapter_number,
                           "unnumbered_ordinal_in_chapter": r.ordinal, "source_file_line": r.source_line,
                           "note": "unnumbered in the source file; cite by book and chapter"}
            passages.append(PassageRecord(
                id=pid, source_id=sid, reference=ref, sequence=i,
                parent_id=f"{sid}:book:{r.book_number}" if r.book_number is not None else None,
                original_text=r.text, normalized_text=normalize_hadith_search(r.text),
                normalized_text_alt=normalize_for_search(r.text),
                metadata={
                    "collection": col["collection"], "collection_ar": col["collection_ar"],
                    "hadith_number": str(r.number) if r.number is not None else None,
                    "numbers_covered": r.numbers_covered, "locator": locator, "chapter_number": r.chapter_number,
                    "numbering": col["numbering"], "book": r.book, "book_number": r.book_number,
                    "chapter": r.chapter, "narrations": r.narrations,
                    "grading": "SAHIHAYN", "grading_ar": (f"من الأحاديث المسندة المرقّمة في {col['collection_ar']}" if r.number is not None
                                   else f"من روايات {col['collection_ar']} المسندة (غير مرقّمة في الملف المصدر)"),
                    "grading_source": g["rule"], "grading_authority": g["grading_authority"],
                    "grading_generated_by_model": False,
                    "source_file_line": r.source_line,
                },
            ))
        insert_passages(conn, passages)
        out[sid] = {k: (v if not isinstance(v, list) else len(v)) for k, v in stats.items()}
    return out
