"""Generate frontend demo examples from the VERIFIED corpus (Quran text is read from the DB, never typed).

Only inputs are written (quote + claim + what the example is meant to demonstrate). Results are NOT
stored: the UI sends each example through the real pipeline. The script runs every example through the
pipeline once and fails if it does not demonstrate what it claims to (e.g. the "ambiguous" example must
really be ambiguous in the current corpus).

usage: python scripts/make_demo_examples.py
"""

import json
import sys

from _common import DEFAULT_DB, ROOT

from app.core.config import Settings
from app.schemas.analyze import AnalyzeRequest
from app.services.analysis_pipeline import AnalysisPipeline

OUT = ROOT / "frontend" / "src" / "examples.json"


def main() -> int:
    p = AnalysisPipeline(Settings(database_path=str(DEFAULT_DB)), ROOT, provider=None)

    def emlaey(pid, a=None, b=None):
        return " ".join(p.repo.get(pid).metadata["publisher_aya_text_emlaey"].split()[a:b])

    def hadith_matn_start(pid, mark, n):
        """First n words after the first opening quotation mark of the stored text (read from the DB)."""
        t = p.repo.get(pid).original_text
        return " ".join(t[t.index(mark) + 1:].split()[:n]).rstrip("،")

    examples = [
        {"id": "exact", "label": "اقتباس كامل", "demonstrates": "EXACT",
         "quote": emlaey("quran:1:2"), "claim": "هذا النص من سورة الفاتحة"},
        {"id": "partial", "label": "اقتباس مقتطع", "demonstrates": "PARTIAL",
         "quote": emlaey("quran:2:191", 0, 4), "claim": "الآية تأمر بقتل غير المسلمين مطلقا"},
        {"id": "ambiguous", "label": "عبارة متكررة", "demonstrates": "AMBIGUOUS",
         "quote": emlaey("quran:55:13"), "claim": "هذه الآية وردت مرة واحدة في القرآن"},
        {"id": "hadith", "label": "حديث من الصحيحين", "demonstrates": "PARTIAL", "source_type": "hadith",
         "quote": hadith_matn_start("hadith:bukhari:1", "«", 8),
         "claim": "هذا الحديث يدل على أن الأعمال بالنيات"},
        {"id": "not_found", "label": "نص غير موجود", "demonstrates": "NOT_FOUND",
         "quote": "من جد وجد ومن زرع حصد", "claim": "هذا نص من القرآن الكريم"},
        {"id": "hadith_not_found", "label": "قول متداول", "demonstrates": "NOT_FOUND",
         "quote": "اطلبوا العلم ولو بالصين", "claim": "هذا حديث صحيح"},
    ]
    for ex in examples:
        r = p.analyze(AnalyzeRequest(quote=ex["quote"], claim=ex["claim"]))
        got = r.quote_analysis.match_status
        st = r.source.source_type if r.source else None
        if got != ex["demonstrates"] or ("source_type" in ex and st != ex["source_type"]):
            print(f"FAIL: example {ex['id']} produced {got}, expected {ex['demonstrates']}")
            return 1
        print(f"ok  {ex['id']:16s} -> {got} {(r.source.source_id + ' ' + r.source.reference) if r.source else ''}")
    OUT.write_text(json.dumps({"_note": "Generated by scripts/make_demo_examples.py from the verified corpus. "
                                        "Inputs only; results come from the live pipeline.",
                               "corpus_version": p.corpus_version, "examples": examples},
                              ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
